{
	'ACHIEVEMENT_PAGES':{
		0:{
			'name':'页面一',
			'background':'main_back.png',
			'pos':((0,0),(0,0),(1,0),(1,0))
		},
		1:{
			'name':'页面二',
			'background':'frame_back.png',
			'pos':((0,0),(0,0),(1,0),(1,0))
		},
		2:{
			'name':'页面三',
			'background':'default.png',
			'pos':((0,0),(0,0),(1,0),(1,0))
		}
	},
	'ACHIEVEMENT_ITEMS':{
		0:{
			'name':'wxh天下第一',
			'icon':'default.png',
			'text':'wxh天下第一的描述',
			'cond':'wxh天下第一的条件描述',
			'page':0,
			'pos':((0.4,0),(0.4,0),(0.06,0),(0.06,0))
		},
		1:{
			'name':'wxh当然天下第一',
			'icon':'default.png',
			'text':'wxh当然天下第一的描述',
			'cond':'wxh当然天下第一的条件描述',
			# 定义成就图标的坐标
			'page':0,
			'pos':((0.6,0),(0.5,0),(0.06,0),(0.06,0))
		},
		2:{
			'name':'wxh乃天下第一',
			'icon':'default.png',
			'text':'wxh乃天下第一的描述',
			'cond':'wxh乃天下第一的条件描述',
			# 定义成就图标的坐标
			'page':1,
			'pos':((0.4,0),(0.4,0),(0.06,0),(0.06,0))
		},
		3:{
			'name':'wxh是为天下第一',
			'icon':'default.png',
			'text':'wxh是为天下第一的描述',
			'cond':'wxh是为天下第一的条件描述',
			# 定义成就图标的坐标
			'page':1,
			'pos':((0.4,0),(0.4,0),(0.06,0),(0.06,0))
		}
	}
}